theme: jekyll-theme-minimal
markdown: kramdown
title: Nellyyi's Notes 
description: I write about machine learning, computer vision and science. This page is to keep track of my current favourite networks. 
