theme: jekyll-theme-cayman
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
title: Nellyyi's Notes 
description: I write about machine learning, computer vision and science. This page is to keep track of my current favourite networks. 

show_excerpts: true # Show excerpts of posts on the home page
permalink: /:categories/:title # Don't show the date of the post in the URL


# Build settings
markdown: kramdown
theme: cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap # I added this to automatiacally generate a sitemap.xml

# These are default variables for my pages
# Any file in the `_posts` directory gets a default layout of `post`, 
# so I don't have to specify it manually
defaults:
    - scope:
        path: _posts
      values:
        layout: post
